### ISSUE TITLE
Encoding CSV support?

### ISSUE THREAD

**Issue by andermoran** [123456abcdef/cr-sc-dump#11]
I've seen other tools to encode decoded .sc files but I  haven't found one that works. I tried [this one](https://github.com/proydakov/supercell_resource_decoder) but it doesn't work properly. Will encoding support for .csv files ever be released?

**Comment by 123456abcdef** [comment]
I assume you mean that the decoded and then re-encoded file is not exactly the same as the initial file?
The problem here is that the compression settings are unknown (see [here](https://github.com/proydakov/supercell_resource_decoder/blob/099b1f7129118e3186ccaa756ed60c3f96bba3cc/lib_csv.py#L57)). Also I'm not even sure if LZMA compression is deterministic, that means if compressing the same data will always yield the same results.
But I guess it doesn't even matter cause if the games LZMA algorithm can decompress the data that will be good enough.
