### ISSUE TITLE
Failed to decrypt .sc file - Unknown Header exception

### ISSUE THREAD

**Issue by dancechart** [123456abcdef/cr-sc-dump#29]
Tried via VSCode terminal `py dumpsc.py C:\Users\Admin\Main\resources\assets\sc\boats.sc`. Got Unknown Header exception. Adding `--old` doesn't change anything.

**Comment by 123456abcdef** [comment]
Most likely that file does not contain assets. Please try a `*_tex.sc` file.

**Comment by dancechart** [comment]
Still shows the same exception, tried multiple `*_tex.sc` files... All libraries are downloaded, VSCode doesn't show any issues.
![cr-sc-dump-issue](https://github.com/123456abcdef/cr-sc-dump/assets/171438133/596309d0-faaa-400f-9160-f42c48af3afa)

That's what `data[0]`, `data[:2]` and `data[:4]` contains when trying to read `*_tex.sc` file.
![cr-sc-dump-issue-1](https://github.com/123456abcdef/cr-sc-dump/assets/171438133/27d43cc5-0910-4ae3-8c36-52e397d2126a)

For `*.sc` file output is different.
![cr-sc-dump-issue-2](https://github.com/123456abcdef/cr-sc-dump/assets/171438133/a8d0dc42-2747-4420-8b4a-04ce18249ec5)

 Adding or removing `--old` doesn't affect that in both cases.

**Comment by CharlieeChaser** [comment]
Hi guys, I'm not really here to report a problem and I sincerely apologize for that, but I didn't find any other way to communicate with you and the only mail I found (belonging to Mr. Hélio Costa) still hasn't answered me 🥹
I have absolutely no idea how these things work since I know nothing about programming 🥹
That's why I wanted to ask for your help to decode this file called "emotes_rascals_lovegum_dl.sc" which corresponds to the emote of the girl chewing gum in Clash Royale, as far as I know there are the png sprites of it and I want to get them to draw it vector animated to use it in future videos 😊
I'm attaching a link to my GDrive with the file "emotes_rascals_lovegum_dl.sc", an example of what the sprites should look like, and a picture of the emote I'm referring to.
I hope you can help me with this, and if not I'll understand, but thanks for reading 🥹

https://drive.google.com/file/d/1RiMfIDxqCu_1ldMYh6yxGV4P8nM09ICP/view?usp=drive_link
![42388030-e0085460-814c-11e8-9689-17d4b30ca2f8](https://github.com/123456abcdef/cr-sc-dump/assets/172232928/3ff09331-8f3c-4be1-b41c-a86f0b30b08c)
![emotes_rascals_lovegum](https://github.com/123456abcdef/cr-sc-dump/assets/172232928/f08a4c46-c121-43b9-b9b5-aff46e45e6b8)

**Comment by 123456abcdef** [comment]
@dancechart Which game do the files come from?

@CharlieeChaser The first sprite you attached does not match `emotes_rascals_lovegum_dl.sc`. You can extract the png from it using `python dumpsc.py emotes_rascals_lovegum_dl.sc --old`.
To get an animated version you would need to parse the file further. After the image there is additional info in the file. I assume it tells you how to cut the sprites, rotate, transform, and overlap to get an animated image.
[sc_decode](https://github.com/Galaxy1036/sc_decode) tried to parse these information. I don't know if there is public script you could use.

**Comment by dancechart** [comment]
@123456abcdef from Boom Beach. If you need an archive with all `.sc` files I could find there after unpacking an `.apk`, let me know.

**Comment by 123456abcdef** [comment]
@dancechart Works just fine for me. If you look in `<apk-root>/assets/fingerprint.json` at the end of the file. `sha: 4aac756f2f41dc68fd7552a91005f55065b6afd, version: 52.103.1`. Is your version newer or older? sha1 of the file I used is `38ede3081542ecc02077b7301cbfbdb48c41e6d6  boats_tex.sc`. First to bytes of the file should be `0x53 0x43` in hex or `SC` in ASCII. Seems to be not the case for your file.

@CharlieeChaser Getting the `*_tex.sc` files seems to me more complicated than running a Python script. Please try yourself using this script. I won't share copyrighted data.

**Comment by dancechart** [comment]
@123456abcdef my version is older, `"sha":"9227415f159f7ff0ad1df05e03b172d1cc11227c","version":"50.101.1"`. Will try out the latest version, thank you for the help.
